### ISSUE TITLE
Frontend Icon mit FontAwesome Icons

### ISSUE THREAD

**Issue by swinde** [swinde/contao4-downloadarchiv#12]
Austausch der Icons gegen FontAwesome Icons

**Comment by swinde** [comment]
Linkgedankenstützen:
https://de.contaowiki.org/Font-awesome
https://github.com/netzmacht/contao-font-awesome-inserttag/blob/master/composer.json

**Comment by wiphi** [comment]
Ich schau mir mal an wie man die Icons rein laden könnte. Ich denke da an eine Option in den Archiven, wo man wählen kann, welche Icons man haben möchte. Voraussetzung ist dann das netzmacht/contao-font-awesome package.

**Comment by wiphi** [comment]
@swinde ich habe mir mal ein paar Sachen angeschaut, wie man die font-awesome Icons einbinden könnte:
Ich würde das contao4-downloadarchive nicht vom font-awesome Package abhängig machen wollen, eher als empfohlenes Zusatzpaket.
Wenn das installiert ist, könnte man anbieten, über den  [netzmacht/contao-icon-wizard](https://github.com/netzmacht/contao-icon-wizard) für jeden Download ein Icon auszuwählen.

Persönlich wäre es mir lieber gewesen, wenn das Icon anhand des Dateityps automatisch gewählt werden könnte. Aber dafür fehlen ein paar Informationen und ich weiß nicht, ob das so überhaupt gebraucht wird.

**Comment by swinde** [comment]
Vielen Dank für deine Recherchen! Ich glaube der große Aufwand lohnt sich nicht. Ich möchte das ganze nicht zu sehr überfrachten.
Ich denke wir lassen das erst einmal so.

**Comment by wiphi** [comment]
Heißt du willst keine font-awesome Icons mehr einbinden? Oder die Variante über die Auswahl?

**Comment by swinde** [comment]
Ich frage mich zur Zeit, ob der Aufwand den Du haben wirst, ich bekomme das eh nicht hin, gerechtfertigt ist!
Mal eine kurze Analysse:
Welche Dateien werden den hier zum Download angeboten?
Sicher am häufigsten PDF Dateien, vielleicht noch DOC oder EXCEL. Muss man da noch eine zusätzliche Bibliothek laden? Ich finde Contao seit Composer extem aufgebläht durch diverse Abhängigkeiten.
Bei meinen Projekten habe ich die Bilder im Template ausgeblendet und arbeite mit CSS :bevore

a[href$='.pdf'] {
  &::before{
    font-family: FontAwesome;
    content: "\f1c1";
    margin-right: 5px;
    color: #ba2350;
  }
}
Oder man macht eine if else Abfrage im Template für die ausgewählte Dateiformen. Letztendlich ist jeder Nutzer da ja ganz frei in der Gestaltung.

VG Steffen 
PS Ich möchte Dich aber auch nicht ausbremsen.

**Comment by wiphi** [comment]
Gut :) dann werde ich erstmal nicht weiter aktiv :)
