### ISSUE TITLE
Bitte eine feste Version freigeben

### ISSUE THREAD

**Issue by wiphi** [swinde/contao4-downloadarchiv#13]
Derzeit werden immer die Quellen von dev-master geladen. Für ein stabilen Websitenbetrieb wäre eine feste Version sinnvoll. Könntest Du einen Release (Tag) erstellen, z.B. 2.0.0?

**Comment by swinde** [comment]
Wenn es jetzt auch nicht sehr vorteilhaft für mich ist, ich drücke mich da schon lange drum! Da ich keine Ahnung habe wie das funktioniert! 

Edit: Ist das so richtig?

**Comment by wiphi** [comment]
Passt doch! Danke :)
