### ISSUE TITLE
Contao 3.5.x kompatibel?

### ISSUE THREAD

**Issue by operatorone** [swinde/contao4-downloadarchiv#14]
Hallo, könnte ich diese Erweiterung noch in einer Contao 3.5.33-Instanz einsetzen. Ggf. manuell installieren?

**Comment by wiphi** [comment]
Diese ist nur für Contao 4 geeignet. Evtl. könnte es klappen in dem du das [src/Resources/contao](https://github.com/swinde/contao4-downloadarchive/tree/master/src/Resources/contao) in den `system/modules`-Ordner einer 3.5er Installation kopierst. Ich kann dir aber nur davon abraten.

Wenn du eine lauffähige Version möchtest, welche mit PHP7 kompatibel ist, kannst du meinen Fork benutzen: [wiphi/contao-downloadarchive](https://github.com/wiphi/contao-downloadarchive/tree/php7).

Wenn du in einer 3.5er bereits den Composer (alias Paketverwaltung) verwendest, kannst du diese wie folgt installieren:

1.  Füge im in die `composer.json` mein Repository ein
```
    "repositories": [
        {
            "url": "https://github.com/wiphi/contao-downloadarchive.git",
            "type": "git"
        }
]
```
2. Im `require` Abschnitt fügst du `"felixpfeiffer/contao-downloadarchive": "dev-php7"` hinzu. Damit wird mein Fork mit den PHP7 Korrekturen heruntergeladen und installiert.
3. Wenn du jetzt die Pakete aktualisierst, bekommst du das Package.

Alternativ kannst du dir auch mein Repository im Branch php7 als Zip runterladen und manuell installieren.

**Comment by swinde** [comment]
Danke @wiphi für Deinen Betrag! Ich war im Urlaub und konnte nicht antworten.
