### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by Messa1** [swinde/contao4-downloadarchiv#16]
Hallo gibt es eine Möglichkeit Daten aus der alten Erweiterung zu migrieren?
https://github.com/felixpfeiffer/contao-downloadarchive

Wenn ich dein bundle installiere sehe ich nachher, dass neue Tabellen angelegen werden.
Gibt es danach eine Möglichkeit die original zu migrieren?

lg Matthias

**Comment by wiphi** [comment]
Wir haben eigentlich nichts an den Tabellen geändert. Ich habe letztens selbst eine C3 Modul Installation auf eine C4 Bundle Version geupgraded und da hat er alles übernommen. Kannst Du uns mal ein Screenshot vom Install-Tool zu dem Zeitpunkt zukommen lassen, was er da machen möchte? Interessant wäre auch die Contao Version.

**Comment by Messa1** [comment]
Klar hier.
Contao 3.2 updated auf Contao 4.4
![Bildschirmfoto 2019-03-11 um 17 02 57](https://user-images.githubusercontent.com/3908658/54139902-d420b180-4422-11e9-999c-babd8f4b178e.png)

**Comment by swinde** [comment]
Das ist ein Problem einer früheren Version felixpfeiffer/contao-downloadarchive, da gab es mal so einen Fehler! Kann ich mich dran erinnern!
Da hilft die entweder den Inhalt sichern und nach dem Update wieder einspielen oder die 2 Tabellen vorher umbenennen!
Man kann den Unterschied kaum erkennen! tl_downloadarchiv --> tl_downloadarchiv**e**
PS: Man sollte vor dem Update erstmal Vorraussetzungen schaffen!
Version Contao 3.5.37 ist aktuell. Die Änderung der Tabellen wurde in felixpfeiffer/contao-downloadarchive V1.0.0 gemacht! Die letzte Version ist 3.0.4!

**Comment by Messa1** [comment]
Oky, dann benenne ich sie um. Melde mich noch mit einem Feedback.

**Comment by Messa1** [comment]
Hat geklappt.

**Comment by wiphi** [comment]
BTW: hatte felixpfeifer eine runonce-Datei extra dafür programmiert. https://github.com/felixpfeiffer/contao-downloadarchive/commit/33e8fbd4a87036e43df36e99b900e36ef9bb617b
Sollte also kein Problem sein, wenn man die aktuellste Version von felixpfeifer hat, bevor man zu dieser C4 Bundle-version wechslt.
