### ISSUE TITLE
PHP 8.1 Support

### ISSUE THREAD

**Issue by kgollmer** [swinde/contao4-downloadarchiv#18]
Hi guys, I'm currently testing my website on new PHP 8.1, will there be an update of your (great!) package any time soon to support the new php-version?

**Comment by swinde** [comment]
Version 2.1 is released for Php 8.1 and Contao >= 4.9

**Comment by rabauss** [comment]
Is it intended that you support PHP 8.1 but not 8.0?

**Comment by swinde** [comment]
Das Ticket lautete  PHP 8.1 Support #18, ich habe die composer.json auf 8.0 geändert.
