### ISSUE TITLE
composer.json Package Name

### ISSUE THREAD

**Issue by wiphi** [swinde/contao4-downloadarchiv#2]
Das Repo heißt `contao4-downloadarchiv`, in der composer.json sollte der Name dann auch so heißen. Derzeit lautet dieser noch `contao4-downloadarchive`.

Ich denke eine Vereinheitlichung nach Deutsch wäre passender. Oder alles nach Englisch :)

**Comment by swinde** [comment]
Du hast recht, werde ich gleich ändern. Ich stehe mit dem Englischem etwas auf Kriegsfuss. 

Ich habe lieber den Reponamen geändert, da mehrere Archive anlegt werden können.

**Comment by swinde** [comment]
Wenn Du möchtest, kannst du ja einen Fork erstellen.

**Comment by wiphi** [comment]
Das mach ich jetzt auch ;) Nur wegen solchen kleinen Kleinigkeiten hat sich das nicht gelohnt :)
