### ISSUE TITLE
Ordner einlesen lassen

### ISSUE THREAD

**Issue by Joam55** [swinde/contao4-downloadarchiv#5]
Ich habe einen einen Ordner einlesen lassen, einmal ohne Einschränkung auf Verzeichnisendung PDF, und einmal mit PDF.
Der Ordner hat mehr als 22 Dateien, davon 10 PDF Dateien.
Es wurden immer 22 Dateien erzeugt, jeder der 22 Dateien hatte den selben Namen und Inhalt.

**Comment by wiphi** [comment]
Das Problem ist bekannt, ich untersuche das gerade in meinem Fork [bugfix-readdir](https://github.com/wiphi/contao4-downloadarchive/tree/bugfix-readdir).
@swinde, du kannst mich gerne dem Issue zuweisen.

**Comment by Joam55** [comment]
Wie mache ich das?

Gruß Achim

**Comment by wiphi** [comment]
@Joam55 Du musst gar weiter unternehmen.
Da ich gerade Geister gejagt habe.. Es gab ein Problem in Contao 4.5.2, welches das Einlesen von Ordnern generell verhinderte. [C4 1328](https://github.com/contao/core-bundle/issues/1328). Das hat mich gerade total raus geschmissen.

**Comment by swinde** [comment]
Hallo wiphi oder darf ich auch Philipp zu Dir sagen?

Wie groß wäre der Aufwand beim Einlesen der Dateien abzuprüfen, ob die Dateien schon in der Datenbank vorhanden sind?
Wenn man den Downloadordner bearbeitet und vergisst den Haken rauszunehmen, liest man sich unter Umständen die 22 Dateien noch mal ein. Das ist nicht lustig die dann wieder löschen zu müssen!

Steffen
