### ISSUE TITLE
Downloadordner bearbeiten

### ISSUE THREAD

**Issue by swinde** [swinde/contao4-downloadarchiv#7]
Hallo wiphi oder darf ich auch Philipp zu Dir sagen?

Wie groß wäre der Aufwand beim Einlesen der Dateien abzuprüfen, ob die Dateien für diesen Ordner schon in der Datenbank vorhanden sind?
Wenn man den Downloadordner bearbeitet und vergisst den Haken rauszunehmen, ließt man sich unter Umständen die 22 Dateien noch mal ein. Das ist nicht lustig die alle wieder löschen zu müssen!

Steffen

**Comment by wiphi** [comment]
Klar Steffen ;), wie wollen wir das lösen?
- Variante 1: Bereits hinzugefügte Items werden aus dem Archiv entfernt und das Verzeichnis neu eingelesen: Dann passt das Verzeichnis immer zu den Elementen
- Variante 2: Bereits eingelesene Elemente bleiben erhalten und wir prüfen, ob das Element bereits vorhanden ist? Dann würde aber u.U. der Pfad der hinterlegt ist, nicht zu den Elementen passen, z.B. wenn man erst ein Verzeichnis einliest und dann noch ein anderes.

Weitere Vorschläge?

**Comment by swinde** [comment]
Also Variante 1 würde mir vollkommen ausreichen. Ich möchte nur die Mehrarbeit verhindern, die entsteht wenn man den Haken vergisst zu deaktivieren. 
Da ich überhaupt nicht einschätzen kann wie hoch der Programmieraufwand ist (ich bin da eher Laie, was programmieren angeht), überlasse ich die Entscheidung dir.

**Comment by wiphi** [comment]
Ich finde Variante 1 auch besser. Da haben wir nur ein Problem. Lösche ich die Items, gehen auch die Einstellungen, wie Bild und Texte in den Items verloren. Da muss ich mir was einfallen lassen.

**Comment by swinde** [comment]
Stimmt das hatte ich nicht bedacht!
