### ISSUE TITLE
Schönheitsfehler in der Downloadarchiv-Konfiguration

### ISSUE THREAD

**Issue by wiphi** [swinde/contao4-downloadarchiv#9]
Im DCA ist noch ein Anzeige-Fehler innerhalb der Auswahl des Einlese-Verzeichnisses.

![2018-01-29 22_13_22-dca_downloadarchive](https://user-images.githubusercontent.com/25878910/35534805-eae4ab68-0541-11e8-938f-cea060bf7bb0.jpg)

**Comment by swinde** [comment]
Stimmt, sieht komisch aus, das schaue ich mir mal an. Ich möchte gern etwas dazu lernen.

**Comment by wiphi** [comment]
Auch wenn schon etwas älter, trotzdem noch aktuell [DCA Konfiguration in Contao](https://docs.contao.org/books/manual/3.3/de/06-Data-Container-Arrays.html)
Vielleicht hilft dir das :) Ist nicht schwer ;)

**Comment by swinde** [comment]
Behoben
